### ISSUE TITLE
AuthlibBaseError not caught in Flask blueprint

### ISSUE THREAD

**Issue by rschroll** [authlib/loginpass#13]
We are using the Flask blueprint to enable OAuth sign-on with Github.  For reasons not yet understood, Github stopped accepting our client_secret.  This caused authlib to raise an AuthlibBaseError when the flask blueprint code called `remote.authorize_access_token()`.  As the blueprint code doesn't handle this error, a 500 was returned.  I would prefer that this error be caught and passed into the `handle_authorize` function, so that we can react to the problem.  If this seems reasonable, I'd be happy to take a stab at a PR.

We are running loginpass 0.2.1 with authlib 0.10 and flask 1.0.2 on Python 3.7.  The relevant part of the traceback follows:
```
  File "/env/lib/python3.7/site-packages/loginpass/_flask.py", line 47, in auth
    token = remote.authorize_access_token()
  File "/env/lib/python3.7/site-packages/authlib/flask/client/oauth.py", line 261, in authorize_access_token
    token = self.fetch_access_token(redirect_uri, request_token, **params)
  File "/env/lib/python3.7/site-packages/authlib/client/client.py", line 174, in fetch_access_token
    token = session.fetch_access_token(token_endpoint, **kwargs)
  File "/env/lib/python3.7/site-packages/authlib/client/oauth2_session.py", line 203, in fetch_access_token
    return self._parse_and_validate_token(resp.json())
  File "/env/lib/python3.7/site-packages/authlib/client/oauth2_session.py", line 333, in _parse_and_validate_token
    raise OAuthError(error=error, description=description)
authlib.common.errors.AuthlibBaseError: incorrect_client_credentials: The client_id and/or client_secret passed are incorrect."  
```

**Comment by lepture** [comment]
I don't think it should be caught by `handle_authorize`. Developers should know this error from log or sentry so that they can fix things.

But if you want to catch the error, you can handle them with Flask `errorhandler` http://flask.pocoo.org/docs/1.0/errorhandling/#error-handlers

```py
@app.errorhandler(authlib.client.OAuthError)
def handle_bad_request(e):
    return 'bad request!', 400
```

**Comment by rschroll** [comment]
Fair enough.  This splits error handling code, but maybe it's a sign it should be abstracted out of the handle_authorize function anyway.  Easy enough.

Thanks for the pointer!
