### ISSUE TITLE
Clarify LICENSE 

### ISSUE THREAD

**Issue by jamielennox** [authlib/loginpass#16]
The open source license in the repo is very clearly AGPLv3 whereas the link in the readme says: 

> Loginpass is a group member of Authlib, it is licensed under AGPLv3+. Authlib commercial license applies to this project too, you can get a commercial license at Authlib Commercial Plans.

The page at which says that open source products fall under the BSD license. I take it that this means authlib itself falls under BSD, but loginpass is AGPL?

**Comment by jamielennox** [comment]
Ah, i didn't know about: https://blog.authlib.org/2019/switch-to-bsd-license

So will loginpass fall under the same rules?

**Comment by lepture** [comment]
Yes, it will be licensed under BSD.

**Comment by lepture** [comment]
license is updated to BSD.
