### ISSUE TITLE
loginpass connection classes aren't automatically initialized with their configuration

### ISSUE THREAD

**Issue by salty-horse** [authlib/loginpass#19]
It makes sense for the various connection classes to be usable on their own:

```python
from loginpass.google import Google
oauth_client = Google(
        GOOGLE_KEY,
        GOOGLE_SECRET)
# Do stuff with the client
```
But it this OAuth client isn't automatically initialized with the URLs and scopes defined in `OAUTH_CONFIG`, so it's defeats the purpose of these special classes. Their purpose is to contain this custom configuration.

Would it make more sense to initialize them? Here's a diff against loginpass 0.2.1:
```diff
diff --git a/loginpass/_core.py b/loginpass/_core.py
index 61257aa..e9b4055 100644
--- a/loginpass/_core.py
+++ b/loginpass/_core.py
@@ -7,9 +7,15 @@ class OAuthBackend(OAuthClient):
     """Backend for OAuth Registry"""
     OAUTH_TYPE = None
     OAUTH_NAME = None
-    OAUTH_CONFIG = None
+    OAUTH_CONFIG = {}
     JWK_SET_URL = None
 
+    def __init__(self, *args, **kwargs):
+        for k, v in self.OAUTH_CONFIG.items():
+            if k not in kwargs:
+                kwargs[k] = v
+        OAuthClient.__init__(self, *args, **kwargs)
+
     def fetch_jwk_set(self, force=False):
         if not self.JWK_SET_URL:
             return None
```

**Comment by salty-horse** [comment]
It would also be nice if Google (and others) will initialize `refresh_token_url` (which in the case of Google, it's the same as `access_token_url`

**Comment by lepture** [comment]
Loginpass should be used with Authlib Flask or Django client.
