### ISSUE TITLE
local url when registering blueprint

### ISSUE THREAD

**Issue by alaintxu** [authlib/loginpass#29]
I'm using loginpass with flask inside a docker container.

`application.register_blueprint(bp, url_prefix='/oauth/{}'.format(backend.OAUTH_NAME))`

when accessing to:

> https://-my-public-address-/oauth/google/login

it gives the next message:

> Invalid parameter value for redirect_uri: Non-public domains not allowed: http://-docker-url-:8000/oauth/google/auth

Is there any option to send my public address instead of the docker one for the correct redirection?

**Comment by lepture** [comment]
Not an issue of loginpass. You need to understand how `url_for` with `_external=True` works in Flask. It depends on what "wsgi server" you are using, and you also need to create a proper configure for server like nginx.

You may need to provide more information to solve your problem. I suggest that you ask the question in StackOverflow. Your question should not be related to loginpass. Here is a simple mock up of your problem:

```python
@app.route('/')
def home():
    full_url = url_for('home', _external=True)
    return full_url
```

Good luck.
