### ISSUE TITLE
Github OAuth with non public email 

### ISSUE THREAD

**Issue by kairichard** [authlib/loginpass#32]
The `UserInfo` object does not contain the `email` when requesting a non-public email with `{'scope': 'user:email'}`. As a workaround, it is suggested to get the email with the token that was received see - https://stackoverflow.com/questions/35373995/github-user-email-is-null-despite-useremail-scope 

A possible implementation would extend `GitHub.profile` with `self.get("user/emails")` and use whatever is returned there in case the initial email is `None`. Would you accept PR on this?

**Comment by lepture** [comment]
@kairichard Yes, please.

**Comment by kairichard** [comment]
It would probably go in this direction - does that seem reasonable to you?

```python
class GithubPrivateEmail(GitHub):

    def profile(self, **kwargs):
        profile = super().profile(**kwargs)
        if profile.get("email") is not None:
            return profile

        resp = self.get("user/emails")
        resp.raise_for_status()
        data = resp.json()
        # There should only be one `primary`
        profile["email"] = next(email["email"] for email in data if email["primary"])
        return profile
```

**Comment by lepture** [comment]
@kairichard how about just re-implement `GitHub#profile` method?

**Comment by kairichard** [comment]
@lepture would also work yes, going to come back with a PR next week.
