### ISSUE TITLE
deprecated LinkedIn v1 API

### ISSUE THREAD

**Issue by xofbd** [authlib/loginpass#39]
We use loginpass in our organization and noticed last week that people were unable to login using LinkedIn. Logs showed a 410 which lead us to realize that LinkedIn has a v2 for their web API and more than likely had deprecated v1, which loginpass uses.

We actually forked loginpass and made changes to get it to work. It does appear to be working now so the plan is to soon open up PR with the changes. Here's the repo of our fix: https://github.com/thedataincubator/loginpass

**Comment by lepture** [comment]
updated to v2
