### ISSUE TITLE
LinkedIn does not return email.

### ISSUE THREAD

**Issue by jckw** [authlib/loginpass#44]
Using the default LinkedIn implementation, no email address is returned. 

For example:

```python
oauth = OAuth()


def login_via_linkedin(request, user_info):
    user = None
    print(user_info) // returns all the user_profile fields, but no email


def handle_authorize(request, remote, token, user_info=None):
    print(remote.name)
    if user_info is None:
        return redirect("http://localhost:8000/login-failed")

    if remote.name == LinkedIn.OAUTH_NAME:
        login_via_linkedin(request, user_info)
    else:
        raise ValueError(
            f"Tried to log in with an unsupported remote server {remote.name}."
        )

    return redirect("http://localhost:8000/")


urlpatterns = [
    path(
        "linkedin/",
        include(create_django_urlpatterns(LinkedIn, oauth, handle_authorize)),
    ),
]
```

My LinkedIn application also includes the email address permission (as all default apps do):

![image](https://user-images.githubusercontent.com/11884004/65641555-0079d500-dfe5-11e9-99c2-e0c0c34caca9.png)

This is possibly something wrong with my implementation. My settings do not specify the email scope since I assume it is included by default.

**Comment by lepture** [comment]
@jckw can you debug for https://github.com/authlib/loginpass/blob/master/loginpass/linkedin.py#L68 this `get_user_email` method?

**Comment by jckw** [comment]
Resolved this by changing the get_user_email method. The issue is that the format is not what the code expects (possibly due to a new API). 

The data comes in the format:
```
{"elements": [{"email": "username@example.com"}]}
```

```python
    def get_user_email(self, **kwargs):
        url = "emailAddress?q=members&projection=(elements*(handle~))"
        resp = self.get(url, **kwargs)
        resp.raise_for_status()
        data = resp.json()

        handle = data.get("elements")[0].get("handle~") # this changed
        if handle:
            return handle.get("emailAddress")
```

**Comment by lepture** [comment]
Fixed in master code.
