### ISSUE TITLE
OAUTH_BACKENDS missing linkedin

### ISSUE THREAD

**Issue by ravishan16** [authlib/loginpass#60]
OAUTH_BACKENDS in __init.py is missing LinkedIn

`
OAUTH_BACKENDS = [
    BattleNet, Twitter, Facebook, Google, GitHub, Dropbox, Instagram, Reddit,
    Gitlab, Slack, Discord, StackOverflow, Bitbucket, Strava, Spotify, Yandex,
    Twitch, VK
]`

**Comment by lepture** [comment]
No `OAUTH_BACKENDS` in master code now.
