### ISSUE TITLE
GitLab OAuth Always defaults to 'read_user' permission 

### ISSUE THREAD

**Issue by BaronLR** [authlib/loginpass#61]
in `gitlab.py`   

line 35: `'client_kwargs': {'scope': 'read_user'},`

this causes a lot of confusion when you set your scope in the GitLab Application Register to 'api' for example, which is a higher scope. Then every request made using this wrapper defaults to 'read_user' so you get 'access denied' 

I would suggest the parent method
`def create_gitlab_backend(name, hostname):` 
takes in `scope` as a variable to prevent future confusion

**Comment by lepture** [comment]
You could rewrite it in your configuration:

```
GITHUB_CLIENT_KWARGS = {'scope': '...'}
```
