### ISSUE TITLE
flask_example - 'RemoteApp' object has no attribute 'parse_openid' 

### ISSUE THREAD

**Issue by outofsyncme** [authlib/loginpass#62]
I'm getting AttributeError: 'RemoteApp' object has no attribute 'parse_openid' using https://github.com/authlib/loginpass/commit/32b565e998fde75114fd10f2cd7a76e80c66ea1b with Authlib v0.14.3

https://github.com/authlib/loginpass/blob/d89fddebb0b516c8429f1b2cde7ff000a6f08a93/loginpass/_flask.py#L62

Should it be:
`user_info = remote.parse_id_token(token)`

At least that what the demo-oauth-client has:

https://github.com/authlib/demo-oauth-client/blob/0a6aa9600d8ed1d9cc9f1e8563710c4c0c9db8fc/flask-google-login/app.py#L36

thanks!

**Comment by lepture** [comment]
Thanks for your report.

**Comment by lepture** [comment]
v0.5 is released.
