### ISSUE TITLE
Typo loginpass/_flask.py

### ISSUE THREAD

**Issue by bjonen** [authlib/loginpass#67]
The import on line 83 (https://github.com/authlib/loginpass/blob/66a5c6593f12bc4a537724d7212b1978d275b9fc/loginpass/_flask.py#L83) should read 
`from authlib.integrations.flask_client import RemoteApp as FlaskRemoteApp`
instead of from `authlib.integrations.flask_client import FlaskRemoteApp` with authlib 0.14.

**Comment by lepture** [comment]
It is correct in the code.

**Comment by bjonen** [comment]
You are right, I was looking at an older version of authlib. Sorry for the confusion.
