### ISSUE TITLE
MissingTokenError in github auth when email is private

### ISSUE THREAD

**Issue by woutgg** [authlib/loginpass#70]
For github accounts with their email address set to private, an additional request is made in [`normalize_userinfo`](https://github.com/authlib/loginpass/blob/master/loginpass/github.py#L33) (addressed in issue #32).
This request however, does not pass the authentication token along, causing the MissingTokenError.

**Comment by lepture** [comment]
Can you provide more information?

Framework: Flask or Django?
Authlib version?

**Comment by woutgg** [comment]
Ah sorry yes. This occured with Django 3.1.2, authlib 0.15.2.

**Comment by lepture** [comment]
@woutgg can you check if the latest code works?

**Comment by woutgg** [comment]
Sorry for the delay, it works fine now. Thanks for the fix!
